### **맷플롯립**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

--------------------------------------------------------------------------------
### **지도학습**

훈련 데이터 -> 문제와 정답이 엮여 있는 문제지

아~ 이런 문제에 대해선 이런 게 정답이구나!

테스트 데이터 -> 훈련 데이터로 훈련한 걸 시험해보자!

In [4]:
# zip 함수로 X와 y 분리하기

X , y = zip(['a', '1'], ['b', '2'], ['c', '3'])

print('X 데이터: {}'.format(X))
print('y 데이터: {}'.format(y))

X 데이터: ('a', 'b', 'c')
y 데이터: ('1', '2', '3')


In [6]:
# zip 함수로 2D 텐서에서 X와 y 분리하기

sequence = [['a', '1'], ['b', '2'], ['c', '3']]
X, y = zip(*sequence)
print("X 데이터 : {}".format(X))
print('y 데이터: {}'.format(y))

X 데이터 : ('a', 'b', 'c')
y 데이터: ('1', '2', '3')


In [7]:
# 데이터프레임을 이용하여 분리하기

values = [['당신에게 드리는 마지막 혜택!', 1], # 0은 정상 메일, 1은 스팸 메일
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]

columns = ['메일 본문', '스팸 메일 여부']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 여부
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [9]:
X = df['메일 본문']
y = df['스팸 메일 여부']

print("X 데이터 : {}".format(X.to_list()))
print('y 데이터: {}'.format(y.to_list()))

X 데이터 : ['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
y 데이터: [1, 0, 0, 1]


In [13]:
# Numpy를 이용하여 분리하기

np_array = np.arange(0, 16).reshape((4,4))
print("전체 데이터: ")
print(np_array)

X = np_array[:, :3]
y = np_array[:, 3]
print('-'*30)

print("X 데이터 : ")
print("{}".format(X))
print("y 데이터 : ")
print("{}".format(y))

전체 데이터: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
------------------------------
X 데이터 : [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y 데이터: [ 3  7 11 15]


--------------------------------------------------------------------------------
### **테스트 데이터 분리하기**

In [ ]:
# 사이킷런을 이용해 분리하기

# 예시) X : 독립 변수 데이터, y : 종속 변수 데이터, test_size : 테스트트 데이터 비율, random_state : 난수 시드
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

In [19]:
# 임의의 X, y 데이터

X, y = np.arange(10).reshape((5, 2)), range(5)

print("X 데이터 : ")
print("{}".format(X))
print("y 데이터 : ")
print("{}".format(list(y)))

X 데이터 : 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y 데이터 : 
[0, 1, 2, 3, 4]


In [24]:
# 7:3 비율로 훈련 데이터와 테스트 데이터 분리

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

print('X 훈련 데이터 : ')
print(X_train)
print('X 테스트 데이터 : ')
print(X_test)
print('-' * 30)
print('y 훈련 데이터 : ')
print(y_train)
print('y 테스트 데이터 : ')
print(y_test)

X 훈련 데이터 : 
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
X 테스트 데이터 : 
[[8 9]]
------------------------------
y 훈련 데이터 : 
[0, 1, 2, 3]
y 테스트 데이터 : 
[4]


In [25]:
# random_state의 값을 변경
# random_state에 따라 데이터가 다른 순서로 섞임임
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

print('y 훈련 데이터 :')
print(y_train)
print('y 테스트 데이터 :')
print(y_test)

y 훈련 데이터 :
[4, 0, 3]
y 테스트 데이터 :
[2, 1]


In [26]:
# 실습을 위한 임의의 데이터 생성

X, y = np.arange(0, 24).reshape((12, 2)), range(12)

print("X 데이터 : ")
print("{}".format(X))
print("y 데이터 : ")
print("{}".format(list(y)))

X 데이터 : 
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
y 데이터 : 
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [34]:
# 임의로 훈련 데이터와 테스트 데이터의 개수 정하기

num_of_train = int(len(X) * 0.8)
num_of_test = int(len(X) - num_of_train)

print("훈련 데이터의 크기: ", num_of_train)
print("테스트 데이터의 크기: ", num_of_test)

# 하나의 변수만 사용해서 나눠야 데이터의 누락을 방지할 수 있음음

X_test = X[num_of_train:]
y_test = y[num_of_train:]
X_train = X[:num_of_train]
y_train = y[:num_of_train]

print('X 훈련 데이터 :')
print(X_train)
print('y 훈련 데이터 :')
print(list(y_train))
print('-'*30)
print('X 테스트 데이터 :')
print(X_test)
print('y 테스트 데이터 :')
print(list(y_test))

훈련 데이터의 크기:  9
테스트 데이터의 크기:  3
X 훈련 데이터 :
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
y 훈련 데이터 :
[0, 1, 2, 3, 4, 5, 6, 7, 8]
------------------------------
X 테스트 데이터 :
[[18 19]
 [20 21]
 [22 23]]
y 테스트 데이터 :
[9, 10, 11]
